---
title: "Quiz1 Corrections"
date: "Due: 10/16/2024"
author: "Saransh Rakshak"
output: 
  html_document:
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float: true
---

```{R setup, include=FALSE}
library(dplyr)
library(knitr)
```

# Question 14

### The table below shows frequencies by population (clustered or solitary) and habitat (grasses, waste, or woods) for a fictional sample of mushroom species. The table here shows column proportions corresponding to the frequency table.

```{R}
# Question 14
data <- matrix(c(0.7604167, 0.2244898, 0.5896226,
                 0.2395833, 0.7755102, 0.4103774), 
               nrow = 2, byrow = TRUE)

colnames(data) <- c("grasses", "waste", "woods")
rownames(data) <- c("clustered", "solitary")

kable(data, caption = "Habitat (cols) vs Population (rows) Proportions")
```

 

### Which of the following statements are correct verbal interpretations of the proportions? Select all that are correct. (Two are correct.)

    A. About 41.04% of mushrooms in "woods" habitats are in "solitary" populations. 
    B. About 41.04% of mushrooms in "solitary" populations are in "woods" habitats. 
    C. Mushrooms in "clustered" populations are most likely to be found in "grasses" habitats. 
    D. Mushrooms found in "grasses" habitats are more likely to be in "clustered' than "solitary" populations. 


<span style="color: red;">Answers I chose on the Quiz were **[A, C]**.</span>

    - My selection of A was correct.
    - The proportion of mushrooms in the woods that are solitary is 41.04% (0.4103774) - the value in the "woods" column for solitary mushrooms.
    
    - My selection of C was incorrect.
    - This statement assumes that the proportions in the table represent where clustered mushrooms are found the most. 
    - However, the table shows proportions within each habitat for clustered and solitary mushrooms.
    - The 0.7604167 in the grasses column means that within the grasses habitat, 76.04% of the mushrooms are in clustered populations.
    - This does not tell us that clustered mushrooms are "most likely" to be found in grasses compared to other habitats.
    - For this statement to be correct, we would need the total numbers of clustered mushrooms across all habitats, which is not provided.


<span style="color: green;">- Correct answers are **[A, D]**.</span>
    
    - My selection of A was correct.
    
    - My new selection of D is now correct.
    - Proportion of mushrooms in grasses that are clustered is 76.04%.
    - Proportion of mushrooms in grasses that are solitary is 23.96%.


<br>

# Question 21

### Let $Y$ be a random variable from a $N(1.3, 1^{2})$ distribution.  Find the 95th percentile of the distribution.  Round your answer to three decimal places.

<span style="color: red;">My approach at a solution during the Quiz:</span>

```{R}
# Question 21
# mean and standard deviation
mu <- 1.4
sigma <- 1

# calculate the 95th percentile
q_95 <- quantile(rnorm(10000, mu, sigma), probs = 0.95)

# print the result
print(q_95)
```


    - This code does not work because it uses simulation to approximate the percentile.
    - Unseeded run makes starting point random.
    - Can seed but would be better to use *qnorm()* to get the exact percentile instead of approximating using simulations.


<span style="color: green;">A corrected version of program using qnorm().</span>

```{R}
# Question 21
# mean and standard deviation
mu <- 1.4
sigma <- 1

# calculate the 95th percentile using qnorm
q_95 <- qnorm(0.95, mean = mu, sd = sigma)

# print the result
cat("95 Percentile of Normal Distribution with (mu = 1.4) and (sigma = 1): ", round(q_95, 3))
```











